// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqcwepazixkhzthwqmdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxY3dlcGF6aXhraHp0aHdxbWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjgzNjMsImV4cCI6MjA2NTc0NDM2M30.LLFv56oOiL56Ynm2RDfBlsxFH9goachhle9Eh5SP_FI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);